name: Release Workflow

on:
  push:
    branches:
      - release

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Set up JDK
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      # 3. Build the project using Maven
      - name: Build with Maven
        run: mvn clean package -DskipTests

      # 4. Run tests
      - name: Run tests
        run: mvn test

      # 5. Create a new version tag
      - name: Create Git Tag
        id: tag
        run: |
          version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag -a "v$version" -m "Release v$version"
          git push origin "v$version"

      # 6. Create a release on GitHub
      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: "v${{ steps.tag.outputs.version }}"
          name: "Release v${{ steps.tag.outputs.version }}"
          body: "New release for version v${{ steps.tag.outputs.version }}"
          draft: false
          prerelease: false
